# Change these first
owner: andatoshiki # Your GitHub organization or username, where this repository lives
repo: toshiki-status # The name of this repository

sites:
  - name: "🏠 Toshiki's Homepage"
    url: https://www.toshiki.top/
    icon: https://cdn.toshiki.top/img/favicon.png
  - name: "💨 Toshiki's AC"
    url: https://ac.toshiki.top/
    icon: https://cdn.toshiki.top/img/favicon.png
  - name: "🌮 Toshiki's Proxypool"
    url: https://proxypool.toshiki.top/
    icon: https://cdn.toshiki.top/img/favicon.png
  - name: "🎏 Toshiki's Proxy Subscription"
    url: https://subweb.toshiki.top/
    icon: https://cdn.toshiki.top/img/favicon.png
  - name: "📚 Toshiki's Comment"
    url: https://comment.toshiki.top/
    icon: https://cdn.toshiki.top/img/favicon.png
#   - name: "⚖ Toshiki's CDN"
#     url: https://cdn.toshiki.top
#     icon: https://cdn.toshiki.top/img/favicon.png
  - name: "☁️ Toshiki's OneIndexT Stats"
    url: https://oneindext.toshiki.top/
    icon: https://cdn.toshiki.top/img/oneindext.ico
  - name: "🥓 Toshiki's Image Host"
    url: https://image.toshiki.top/
    icon: https://image.toshiki.top/favicon.ico
  - name: "🍭 Toshiki's Aria2 Panel"
    url: http://download.toshiki.top/
    icon: https://cdn.toshiki.top/img/favicon.png
  - name: "🍛 LostArk Chinese Forum"
    url: https://lost-ark.top/
    icon: https://cdn.jsdelivr.net/gh/white-windmills/lostark-forum@master/img/lostarkFavicon/lostarkFav.png
  - name: "🎠 Toshiki's Gallery"
    url: https://gallery.toshiki.top/
    icon: https://gallery.toshiki.top/favicon.ico             
  - name: "🍿 Toshiki's Upload"
    url: https://upload.toshiki.top/
    icon: https://gallery.toshiki.top/favicon.ico
  - name: "🍩 Toshiki's Navigation"
    url: https://nav.toshiki.top/
    icon: https://gallery.toshiki.top/favicon.ico
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /toshiki-status
  cname: status.toshiki.top
  favicon: https://cdn.toshiki.top/img/favicon.png
  logoUrl: https://cdn.jsdelivr.net/gh/andatoshiki/toshiki-cdn@master/img/status.png
  name: "俊樹 | Status"
  introTitle: "👋 Welcome to 俊樹's site uptime monitor page!"
  introMessage:  🏠 You are now viewing ***俊樹* as well as *Kiwiers org's* sites uptime monitor/status page** powred by **upptime**, you are able to view most of active sites as well as their site live stats on whether they encounters ***uptime*** or ***downtime***, yet site downtime reports are available under [this](https://github.com/andatoshiki/toshiki-status/) repo's issue section!
  navbar:
    - title: Status
      href: /
    - title: About me
      href: https://www.toshiki.top/
  
commitMessages:
  commitAuthorName: "@andatoshiki"
  commitAuthorEmail: "a_toshiki@outlook.com"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: Made with ❤ by [@andatoshiki](//github.com/andatoshiki)
